import AC2TModel from "../models/ac2t.js";
import ProdModel from "../models/prod.js";

class Ac2tController {
    static createDoc = async (req, res) => {
      try {
        const {BOGIE_TYPE_NO,SHIFT,APPLICABLE_WI_NO,FRAME_NO_MAKE,WHEEL_AXLE_NO,BRAKE_CYLINDER_NO_MAKE,VSA_PRIMARY_SUSP_NO_MAKE,VSA_SECONDARY_SUSP_NO_MAKE,LATERAL_SHOCK_ABSORBER_NO_MAKE,BOLSTER_NO_MAKE,Z11_TARE,Z11_TARE_REMARK,Z11_GROSS,Z11_GROSS_REMARK,Z31_TARE,Z31_TARE_REMARK,Z31_GROSS,Z31_GROSS_REMARK,Z41_TARE,Z41_TARE_REMARK,Z41_GROSS,Z41_GROSS_REMARK,Z21_TARE,Z21_TARE_REMARK,Z21_GROSS,Z21_GROSS_REMARK,X_TARE,X_TARE_REMARK,X_GROSS,X_GROSS_REMARK,Z12_PLUS_Z22_BY2_TARE,Z12_PLUS_Z22_BY2_TARE_REMARK,Z12_PLUS_Z22_BY2_GROSS,Z12_PLUS_Z22_BY2_GROSS_REMARK,Z32_PLUS_Z42_BY2_TARE,Z32_PLUS_Z42_BY2_TARE_REMARK,Z32_PLUS_Z42_BY2_GROSS,Z32_PLUS_Z42_BY2_GROSS_REMARK,X14_TARE,X14_TARE_REMARK,X14_GROSS,X14_GROSS_REMARK,X24_TARE,X24_TARE_REMARK,X24_GROSS,X24_GROSS_REMARK,Y13_TARE,Y13_TARE_REMARK,Y13_GROSS,Y13_GROSS_REMARK,Y33_TARE,Y33_TARE_REMARK,Y33_GROSS,Y33_GROSS_REMARK,A_SIDE_TARE,A_SIDE_TARE_REMARK,A_SIDE_GROSS,A_SIDE_GROSS_REMARK,B_SIDE_TARE,B_SIDE_TARE_REMARK,B_SIDE_GROSS,B_SIDE_GROSS_REMARK,TEST_PASSED,requestid,Y_TARE,Y_GROSS, A_TARE,B_TARE,Z133_PLUS_Z23_BY2_TARE,Z133_PLUS_Z23_BY2_TARE_REMARK, X_MINUS_1_TARE,X_MINUS_1_TARE_REMARK,Y_MINUS_1_TARE, Y_MINUS_1_TARE_REMARK, X15_TARE,X15_TARE_REMARK,X25_TARE, X25_TARE_REMARK,Y14_TARE,Y14_TARE_REMARK,Y34_TARE,Y34_TARE_REMARK } = req.body
        const doc =new AC2TModel({
          BOGIE_TYPE_NO: BOGIE_TYPE_NO,
          SHIFT:SHIFT,
          APPLICABLE_WI_NO:APPLICABLE_WI_NO,
          FRAME_NO_MAKE:FRAME_NO_MAKE,
          WHEEL_AXLE_NO:WHEEL_AXLE_NO,
          BRAKE_CYLINDER_NO_MAKE:BRAKE_CYLINDER_NO_MAKE,
          VSA_PRIMARY_SUSP_NO_MAKE:VSA_PRIMARY_SUSP_NO_MAKE,
          VSA_SECONDARY_SUSP_NO_MAKE:VSA_SECONDARY_SUSP_NO_MAKE,
          LATERAL_SHOCK_ABSORBER_NO_MAKE:LATERAL_SHOCK_ABSORBER_NO_MAKE,
          BOLSTER_NO_MAKE:BOLSTER_NO_MAKE,
          Z11_TARE:Z11_TARE,
          Z11_TARE_REMARK:Z11_TARE_REMARK,
          Z11_GROSS:Z11_GROSS,
          Z11_GROSS_REMARK:Z11_GROSS_REMARK,
          Z31_TARE:Z31_TARE,
          Z31_TARE_REMARK:Z31_TARE_REMARK,
          Z31_GROSS:Z31_GROSS,
          Z31_GROSS_REMARK:Z31_GROSS_REMARK,
          Z41_TARE:Z41_TARE,
          Z41_TARE_REMARK:Z41_TARE_REMARK,
          Z41_GROSS:Z41_GROSS,
          Z41_GROSS_REMARK:Z41_GROSS_REMARK,
          Z21_TARE:Z21_TARE,
          Z21_TARE_REMARK:Z21_TARE_REMARK,
          Z21_GROSS:Z21_GROSS,
          Z21_GROSS_REMARK:Z21_GROSS_REMARK,
          X_TARE:X_TARE,
          X_TARE_REMARK:X_TARE_REMARK,
          X_GROSS:X_GROSS,
          X_GROSS_REMARK:X_GROSS_REMARK,
          Z12_PLUS_Z22_BY2_TARE:Z12_PLUS_Z22_BY2_TARE,
          Z12_PLUS_Z22_BY2_TARE_REMARK:Z12_PLUS_Z22_BY2_TARE_REMARK,
          Z12_PLUS_Z22_BY2_GROSS:Z12_PLUS_Z22_BY2_GROSS,
          Z12_PLUS_Z22_BY2_GROSS_REMARK:Z12_PLUS_Z22_BY2_GROSS_REMARK,
          Z32_PLUS_Z42_BY2_TARE:Z32_PLUS_Z42_BY2_TARE,
          Z32_PLUS_Z42_BY2_TARE_REMARK:Z32_PLUS_Z42_BY2_TARE_REMARK,
          Z32_PLUS_Z42_BY2_GROSS:Z32_PLUS_Z42_BY2_GROSS,
          Z32_PLUS_Z42_BY2_GROSS_REMARK:Z32_PLUS_Z42_BY2_GROSS_REMARK,
          X14_TARE:X14_TARE,
          X14_TARE_REMARK:X14_TARE_REMARK,
          X14_GROSS:X14_GROSS,
          X14_GROSS_REMARK:X14_GROSS_REMARK,
          X24_TARE:X24_TARE,
          X24_TARE_REMARK:X24_TARE_REMARK,
          X24_GROSS:X24_GROSS,
          X24_GROSS_REMARK:X24_GROSS_REMARK,
          Y13_TARE:Y13_TARE,
          Y13_TARE_REMARK:Y13_TARE_REMARK,
          Y13_GROSS:Y13_GROSS,
          Y13_GROSS_REMARK:Y13_GROSS_REMARK,
          Y33_TARE:Y33_TARE,
          Y33_TARE_REMARK:Y33_TARE_REMARK,
          Y33_GROSS:Y33_GROSS,
          Y33_GROSS_REMARK:Y33_GROSS_REMARK,
          A_SIDE_TARE:A_SIDE_TARE,
          A_SIDE_TARE_REMARK:A_SIDE_TARE_REMARK,
          A_SIDE_GROSS:A_SIDE_GROSS,
          A_SIDE_GROSS_REMARK:A_SIDE_GROSS_REMARK,
          B_SIDE_TARE:B_SIDE_TARE,
          B_SIDE_TARE_REMARK :B_SIDE_TARE_REMARK     ,                                   
          B_SIDE_GROSS:B_SIDE_GROSS,
          B_SIDE_GROSS_REMARK:B_SIDE_GROSS_REMARK,
          TEST_PASSED:TEST_PASSED,
          Y_TARE:   Y_TARE    ,              
          Y_GROSS:      Y_GROSS,                
          A_TARE:     A_TARE,                  
          B_TARE:    B_TARE,                   
          Z133_PLUS_Z23_BY2_TARE:     Z133_PLUS_Z23_BY2_TARE,  
          Z133_PLUS_Z23_BY2_TARE_REMARK:Z133_PLUS_Z23_BY2_TARE_REMARK,
          X_MINUS_1_TARE:   X_MINUS_1_TARE,            
          X_MINUS_1_TARE_REMARK:   X_MINUS_1_TARE_REMARK,     
          Y_MINUS_1_TARE:               Y_MINUS_1_TARE,
          Y_MINUS_1_TARE_REMARK:       Y_MINUS_1_TARE_REMARK ,
          X15_TARE:  X15_TARE,                   
          X15_TARE_REMARK:      X15_TARE_REMARK,        
          X25_TARE:    X25_TARE,                 
          X25_TARE_REMARK:   X25_TARE_REMARK,           
          Y14_TARE:           Y14_TARE,          
          Y14_TARE_REMARK: Y14_TARE_REMARK,             
          Y34_TARE:    Y34_TARE,                 
          Y34_TARE_REMARK:  Y34_TARE_REMARK,            
















          

        })
        const result = await doc.save()
        const resultid = result._id

        const firmlink=  ProdModel.findOneAndUpdate( 
          requestid, {$push: { AC2_LINK: resultid}}, function(err,data){
            if ( err ) throw err;
            else if(data){
            //console.log( '-- reference created' );
           // console.log('firmlink',data)
          }
        });

        res.status(201).send(result)
      } catch (error) {
        console.log(error)
      }
    }
  }

  export default Ac2tController;